version: "3"

networks:
  workspace:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/19

services:
  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    image: apache
    container_name: ws-apache
    networks:
      - workspace
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
      - ./docker/apache/logs:/var/log/apache2
    depends_on:
      - php7

  php7:
    build:
      context: ./docker/php
    networks:
      - workspace
    image: php7
    container_name: ws-php7
    volumes:
      - ./docker/php/php-fpm.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: ws-mysql
    networks:
      - workspace
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/mycustom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  mongodb:
    image: mongo:latest
    container_name: ws-mongodb
    networks:
      - workspace
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./data/mongodb:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  redis:
    image: redis:4-alpine
    container_name: ws-redis
    networks:
      - workspace
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ws-phpmyadmin
    networks:
      - workspace
    depends_on:
      - php7
      - mysql
    ports:
        - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
    mysql:
      driver: "local"
    redis:
      driver: "local"